using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

namespace FirstPersonSystem
{
    [DefaultExecutionOrder(-1)]
    public class InputManager : MonoBehaviour
    {
        #region Singleton
        private static InputManager _instance;
        public static InputManager Instance { get { return _instance; } }

        // This is the C# class generated by your Input Action Asset
        private FirstPersonInput _controls;

        private void Awake()
        {
            if (_instance != null && _instance != this)
            {
                Destroy(this);
            }
            else
            {
                _instance = this;
                _controls = new FirstPersonInput(); // Initialize your generated class
            }
        }
        #endregion

        private float _moveInputHorizontal, _moveInputVertical, _mouseX, _mouseY;
        private bool _jumpedThisFrame, _sprinting, _crouching, _zoomDown, _zoomUp, _interacted, _interacting, _interactEnd, _flashlight;

        public delegate void InputEvent();
        public event InputEvent OnFlashlight;
        public event InputEvent OnRightMouseDown;
        public event InputEvent OnInteracted;

        private void OnEnable()
        {
            _controls.Enable();
        }

        private void OnDisable()
        {
            _controls.Disable();
        }

        private void Update()
        {
            // Read values from the "Player" Action Map
            Vector2 move = _controls.Player.Move.ReadValue<Vector2>();
            _moveInputHorizontal = move.x;
            _moveInputVertical = move.y;

            Vector2 look = _controls.Player.Look.ReadValue<Vector2>();

            // Note: Gamepad sticks are normalized (0 to 1), while mouse delta is raw pixels.
            // You might need to add a multiplier here later depending on how fast you want the gamepad to look vs the mouse.
            _mouseX = look.x * 0.1f;
            _mouseY = look.y * 0.1f;

            _jumpedThisFrame = _controls.Player.Jump.WasPressedThisFrame();
            _sprinting = _controls.Player.Sprint.IsPressed();
            _crouching = _controls.Player.Crouch.WasPressedThisFrame();

            _zoomDown = _controls.Player.Zoom.WasPressedThisFrame();
            if (_zoomDown) { OnRightMouseDown?.Invoke(); }
            _zoomUp = _controls.Player.Zoom.WasReleasedThisFrame();

            _interacted = _controls.Player.Interact.WasPressedThisFrame();
            if (_interacted) { OnInteracted?.Invoke(); }
            _interacting = _controls.Player.Interact.IsPressed();
            _interactEnd = _controls.Player.Interact.WasReleasedThisFrame();

            _flashlight = _controls.Player.Flashlight.WasPressedThisFrame();
            if (_flashlight) { OnFlashlight?.Invoke(); }
        }

        public float GetInput_Horizontal()
        {
            return _moveInputHorizontal;
        }

        public float GetInput_Vertical()
        {
            return _moveInputVertical;
        }

        public float GetInput_MouseX()
        {
            return _mouseX;
        }

        public float GetInput_MouseY()
        {
            return _mouseY;
        }

        public Vector2 GetInput_Move()
        {
            return new Vector2(_moveInputHorizontal, _moveInputVertical);
        }

        public Vector2 GetInput_Look()
        {
            return new Vector2(_mouseX, _mouseY);
        }

        public bool GetInput_Jumped()
        {
            return _jumpedThisFrame;
        }

        public bool GetInput_Sprinting()
        {
            return _sprinting;
        }

        public bool GetInput_Crouching()
        {
            return _crouching;
        }

        public bool GetInput_ZoomDown()
        {
            return _zoomDown;
        }

        public bool GetInput_ZoomUp()
        {
            return _zoomUp;
        }

        public bool GetInput_Interacted()
        {
            return _interacted;
        }

        public bool GetInput_Interacting()
        {
            return _interacting;
        }

        public bool GetInput_InteractingEnded()
        {
            return _interactEnd;
        }

        // --- Hardware-Specific Inputs ---
        // I left these tied to the physical Mouse, since gamepads don't natively have 
        // a scroll wheel or a middle click. If you build an inventory that uses D-Pad 
        // to scroll, you may want to move these into the PlayerControls asset later!

        public Vector2 GetInput_MousePos()
        {
            if (Mouse.current != null)
                return Mouse.current.position.ReadValue();

            return Vector2.zero;
        }

        public bool GetInput_Flashlight()
        {
            return _flashlight;
        }

        public float GetInput_MouseScrollDelta()
        {
            if (Mouse.current != null)
            {
                float scrollY = Mouse.current.scroll.ReadValue().y;
                if (scrollY > 0) return 1f;
                if (scrollY < 0) return -1f;
            }
            return 0f;
        }

        public bool GetInput_MiddleMouseButtonPressed()
        {
            if (Mouse.current != null)
                return Mouse.current.middleButton.wasPressedThisFrame;

            return false;
        }

        public bool GetInput_AnyMoveInput()
        {
            return _moveInputHorizontal != 0 || _moveInputVertical != 0;
        }
    }
}